name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: true

      - run: pnpm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          branch: gh-pages
          folder: dist-docs
          force: true
